//--- export object begin ---//
instant SimGui::Control "IRCCHATGui" {
	position = "0 0";
	extent = "640 480";
	horizSizing = "right";
	vertSizing = "bottom";
	consoleVariable = "";
	consoleCommand = "";
	altConsoleCommand = "";
	deleteOnLoseContent = "True";
	ownObjects = "True";
	opaque = "False";
	fillColor = "0 0 0";
	selectFillColor = "0 0 0";
	ghostFillColor = "0 0 0";
	border = "False";
	borderColor = "0 0 0";
	selectBorderColor = "0 0 0";
	ghostBorderColor = "0 0 0";
	visible = "True";
	tag = "IDGUI_IRC_CHAT";
	instant FearGui::FGShellBorder {
		position = "0 0";
		extent = "640 480";
		horizSizing = "width";
		vertSizing = "height";
		consoleVariable = "";
		consoleCommand = "";
		altConsoleCommand = "";
		deleteOnLoseContent = "True";
		ownObjects = "True";
		opaque = "True";
		fillColor = "0 0 0";
		selectFillColor = "0 0 0";
		ghostFillColor = "0 0 0";
		border = "False";
		borderColor = "0 0 0";
		selectBorderColor = "0 0 0";
		ghostBorderColor = "0 0 0";
		visible = "True";
		tag = "";
		backgroundBitmap = "Background5.bmp";
		instant Simgui::Control {
			position = "79 97";
			extent = "641 320";
			horizSizing = "center";
			vertSizing = "height";
			consoleVariable = "";
			consoleCommand = "";
			altConsoleCommand = "";
			deleteOnLoseContent = "True";
			ownObjects = "True";
			opaque = "False";
			fillColor = "0 0 0";
			selectFillColor = "0 0 0";
			ghostFillColor = "0.819608 0.945098 0.952941";
			border = "False";
			borderColor = "0 0 1";
			selectBorderColor = "0.772549 0.796078 0.788235";
			ghostBorderColor = "0 0 0";
			visible = "True";
			tag = "";
		};
		
		instant FearGui::FGSimpleText {
			position = "122 141";
			extent = "174 18";
			horizSizing = "center";
			vertSizing = "bottom";
			consoleVariable = "";
			consoleCommand = "";
			altConsoleCommand = "";
			deleteOnLoseContent = "True";
			ownObjects = "True";
			opaque = "False";
			fillColor = "0 0 0";
			selectFillColor = "0 0 0";
			ghostFillColor = "0.666667 0.619608 0";
			border = "False";
			borderColor = "0 0 0";
			selectBorderColor = "0.772549 0.796078 0.788235";
			ghostBorderColor = "0 0 0";
			visible = "True";
			tag = "";
			active = "False";
			messageTag = "";
			fontNameTag = "IDFNT_10_HILITE";
			fontNameTagHL = "IDFNT_10_SELECTED";
			fontNameTagDisabled = "IDFNT_10_DISABLED";
			textTag = "";
			text = "BIG THANKS go out to EVERYONE in the Tribes Community!";
			align = "left";
			textVPosDelta = "0";
		};
	};

		instant FearGui::FGUniversalButton {
			position = "22 0";
			extent = "69 34";
			horizSizing = "right";
			vertSizing = "bottom";
			consoleVariable = "";
			consoleCommand = "$QuickStart = FALSE;";
			altConsoleCommand = "";
			deleteOnLoseContent = "True";
			ownObjects = "True";
			opaque = "False";
			fillColor = "0 0 0";
			selectFillColor = "0.227451 0.239216 0.286275";
			ghostFillColor = "0.227451 0.239216 0.286275";
			border = "False";
			borderColor = "0 0 0";
			selectBorderColor = "0.227451 0.239216 0.286275";
			ghostBorderColor = "0.533333 0.545098 0.537255";
			visible = "True";
			tag = "IDGUI_MAIN_MENU";
			active = "True";
			messageTag = "IDGUI_MAIN_MENU";
			isCheckbox = "False";
			radioTag = "";
			bitmapRoot = "SBB_Play";
			isSet = "False";
			mirrorConsoleVar = "False";
	};
	instant FearGui::FGUniversalButton {
		position = "91 0";
		extent = "66 33";
		horizSizing = "right";
		vertSizing = "bottom";
		consoleVariable = "";
		consoleCommand = "";
		altConsoleCommand = "";
		deleteOnLoseContent = "True";
		ownObjects = "True";
		opaque = "False";
		fillColor = "0 0 0";
		selectFillColor = "0 0 0";
		ghostFillColor = "0.537255 0.521569 0.211765";
		border = "False";
		borderColor = "0 0 0";
		selectBorderColor = "0.772549 0.796078 0.788235";
		ghostBorderColor = "0 0 0";
		visible = "True";
		tag = "IDGUI_TEMP";
		active = "False";
		messageTag = "";
		isCheckbox = "True";
		radioTag = "";
		bitmapRoot = "SBB_Chat";
		isSet = "True";
		mirrorConsoleVar = "False";
	};
	instant FearGui::FGUniversalButton {
		position = "157 0";
		extent = "67 33";
		horizSizing = "right";
		vertSizing = "bottom";
		consoleVariable = "";
		consoleCommand = "$PlayGameGui = \"gui/MainMenu.gui\"; ";
		altConsoleCommand = "";
		deleteOnLoseContent = "True";
		ownObjects = "True";
		opaque = "False";
		fillColor = "0 0 0";
		selectFillColor = "0 0 0";
		ghostFillColor = "0.592157 0.545098 0.498039";
		border = "False";
		borderColor = "0 0 0";
		selectBorderColor = "0.772549 0.796078 0.788235";
		ghostBorderColor = "0 0 0";
		visible = "True";
		tag = "IDGUI_OPTIONS";
		active = "True";
		messageTag = "IDGUI_OPTIONS";
		isCheckbox = "True";
		radioTag = "";
		bitmapRoot = "SBB_Options";
		isSet = "False";
		mirrorConsoleVar = "False";
	};
	instant FearGui::FGUniversalButton {
		position = "570 0";
		extent = "45 33";
		horizSizing = "left";
		vertSizing = "bottom";
		consoleVariable = "";
		consoleCommand = "onQuit();";
		altConsoleCommand = "";
		deleteOnLoseContent = "True";
		ownObjects = "True";
		opaque = "False";
		fillColor = "0 0 0";
		selectFillColor = "0 0 0";
		ghostFillColor = "0.894118 0.737255 0.690196";
		border = "False";
		borderColor = "0 0 0";
		selectBorderColor = "0.772549 0.796078 0.788235";
		ghostBorderColor = "0 0 0";
		visible = "True";
		tag = "IDGUI_MAIN_MENU";
		active = "True";
		messageTag = "";
		isCheckbox = "False";
		radioTag = "";
		bitmapRoot = "SBB_CmdQuit";
		isSet = "False";
		mirrorConsoleVar = "False";
	};
		instant FearGui::FGUniversalButton {
			position = "40 430";
			extent = "82 23";
			horizSizing = "right";
			vertSizing = "top";
			consoleVariable = "";
			consoleCommand = "$QuickStart = FALSE;";
			altConsoleCommand = "";
			deleteOnLoseContent = "True";
			ownObjects = "True";
			opaque = "False";
			fillColor = "0 0 0";
			selectFillColor = "0.956863 0.94902 0.772549";
			ghostFillColor = "0.737255 0.486275 0.039216";
			border = "False";
			borderColor = "0 0 0";
			selectBorderColor = "0.07451 0.086275 0.078431";
			ghostBorderColor = "0.6 0.372549 0.243137";
			visible = "True";
			tag = "";
			active = "True";
			messageTag = "IDGUI_MAIN_MENU";
			isCheckbox = "False";
			radioTag = "";
			bitmapRoot = "BTN_Back";
			isSet = "False";
			mirrorConsoleVar = "False";
		};
};

//--- export object end ---//
